# Generated by Django 3.1.6 on 2021-02-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcName', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=50)),
                ('htmlURL', models.CharField(max_length=200)),
                ('isLocked', models.BooleanField()),
            ],
        ),
    ]
