# Generated by Django 3.1.6 on 2021-02-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='ip',
            field=models.CharField(max_length=30),
        ),
    ]
